root = "."
tmp_dir = "out"

[build]
cmd = "go build -o out/spindle.out cmd/spindle/main.go"
bin = "out/spindle.out"

include_ext = ["go"]
exclude_dir = ["avatar", "camo", "indexes", "nix", "tmp"]
stop_on_error = true
